name: Automated Tests - PR - Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Change env THREE_SCALE_CONNECT_URL from Prod to Stage - Windows
        run: (Get-Content "D:\a\fabric8-analytics-vscode-extension\fabric8-analytics-vscode-extension\src\apiendpoint.ts") | 
          Foreach-Object {$_ -replace "connect-api-2445582058137.production", "analytics-preview-2445582058137.staging" } |  
          Set-Content "D:\a\fabric8-analytics-vscode-extension\fabric8-analytics-vscode-extension\src\apiendpoint.ts"
        
      - name: Change env THREE_SCALE_CONNECT_KEY from Prod to Stage - Windows
        run: (Get-Content "D:\a\fabric8-analytics-vscode-extension\fabric8-analytics-vscode-extension\src\apiendpoint.ts") | 
          Foreach-Object {$_ -replace "ad467b765e5c8a8a5ca745a1f32b8487", "3e42fa66f65124e6b1266a23431e3d08" } |  
          Set-Content "D:\a\fabric8-analytics-vscode-extension\fabric8-analytics-vscode-extension\src\apiendpoint.ts"


      - name: Run UI tests
        uses: GabrielBB/xvfb-action@v1.5
        with:
          run: npm run ui-test

      - name: Upload screenshots - Windows
        uses: actions/upload-artifact@v2
        if: failure()
        with: 
          name: screenshots - Windows
          path: D:\a\fabric8-analytics-vscode-extension\screenshots\*
          retention-days: 2
  