# This is a basic workflow to help you get started with Actions

name: Automated Tests - PR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: gabrielbb/xvfb-action
        # You may pin to the exact commit or the version.
        # uses: GabrielBB/xvfb-action@5801c7b1a0f819d0e162f9d3cfc51c370d241e16
        uses: GabrielBB/xvfb-action@v1.5
        with:
          # Command to execute using xvfb
          run: npm run ui-test
          # Directory to execute command on, defaults to ./
          # working-directory: ./ # optional
          # XServer options
          # options: # optional

      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with: 
          name: screenshots
          path: ~/work/fabric8-analytics-vscode-extension/screenshots/*
          retention-days: 2
  